[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
mysql = {version = "26.0.0", features = ["chrono"]}
chrono = "0.4.40"
noticia = { path = "../noticia" }
serde = "1.0.219"
