[package]
name = "scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["blocking"] }
scraper = "0.23.1"
regex = "1.11.1"
chrono = "0.4.40"
db = {path = "../db"}
mysql = {version = "26.0.0", features = ["chrono"]}
noticia = {path = "../noticia"}