export const BAIRROS = [
  "Açaí",
  "Alvorada", 
  "Amazonas",
  "Araxá",
  "Beirol",
  "Bella Ville",
  "Bioparque",
  "Boné Azul",
  "Brasil Novo",
  "Buritis",
  "Buritizal",
  "Cabralzinho",
  "Cajari",
  "Central",
  "Chefe Clodoaldo",
  "Cidade Nova",
  "Congós",
  "Coração",
  "Fazendinha",
  "Goiabal",
  "Igarapé da Fortaleza",
  "Ilha Mirim",
  "Infraero 1",
  "Infraero 2",
  "Ipê",
  "Jardim América",
  "Jardim das Acácias",
  "Jardim Equatorial",
  "Jardim Felicidade I",
  "Jardim Felicidade II",
  "Jardim Marco Zero",
  "Jesus de Nazaré",
  "KM 9",
  "Lago da Vaca",
  "Lagoa Azul",
  "Laguinho",
  "Macapaba",
  "Marabaixo 1",
  "Marabaixo 2",
  "Marabaixo 3",
  "Marabaixo 4",
  "Marco Zero",
  "Mestre Oscar",
  "Morada das Palmeiras",
  "Muca",
  "Murici",
  "Nova Esperança",
  "Novo Buritizal",
  "Novo Horizonte",
  "Pacoval",
  "Palácio das Águas",
  "Palmares",
  "Pantanal",
  "Parque Aeroportuário",
  "Parque dos Buritis",
  "Parque dos Jardins",
  "Pedrinhas",
  "Perpétuo Socorro",
  "Ponte",
  "Renascer",
  "Sahar",
  "Santa Inês",
  "Santa Rita",
  "São Lázaro",
  "Sol Nascente",
  "Trem",
  "Universidade",
  "Vale Verde",
  "Zerão",
  "Açucena",
  "Mucajá",
  "São José",
  "Miracema",
].sort((a, b) => a.localeCompare(b, "pt-BR"));

export const COOKIE_NAME = "user-bairros";
export const LOCALSTORAGE_KEY = "userBairros";

export const COOKIE_OPTIONS = {
  expires: 365,
  path: "/",
  sameSite: "strict" as const,
}; 